const pathDetails = {
    path1: {
        plotNumber: '1',
        plotSize: '184.32Sqyards',
        plotFacing: 'West',
        name: 'Preetham',
        profession: 'Business',
        status: 'Booked',
        residentOff: 'Guntur',
    },
    path2: {
        plotNumber: '2',
        plotSize: '180.18Sqyards',
        plotFacing: 'West',
        name: 'Sujatha',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Ponnur',
    },
    path3: {
        plotNumber: '3',
        plotSize: '180.18Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path4: {
        plotNumber: '4',
        plotSize: '180.18Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path5: {
        plotNumber: '5',
        plotSize: '176.23Sqyards',
        plotFacing: 'West',
        name: 'Masthan Vali',
        profession: 'Farmer',
        status: 'Sold',
        residentOff: 'Chadol',
    },
    path6: {
        plotNumber: '6',
        plotSize: '211.31Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path7: {
        plotNumber: '7',
        plotSize: '165.05Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path8: {
        plotNumber: '8',
        plotSize: '164.92Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path9: {
        plotNumber: '9',
        plotSize: '172.32Sqyards',
        plotFacing: 'East',
        name: 'Durga Prasad',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Alluru',
    },
    path10: {
        plotNumber: '10',
        plotSize: '212.22Sqyards',
        plotFacing: 'East',
        name: 'Vijaya Lakshmi',
        profession: 'Business',
        status: 'Booked',
        residentOff: 'Nizampatnam',
    },
    path11: {
        plotNumber: '11',
        plotSize: '212.22Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path12: {
        plotNumber: '12',
        plotSize: '212.22Sqyards',
        plotFacing: 'East',
        name: 'Revathi',
        profession: 'House Wife',
        status: 'Sold',
        residentOff: 'Reddypallem',
    },
    path13: {
        plotNumber: '13',
        plotSize: '212.22Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path14: {
        plotNumber: '14',
        plotSize: '907.1Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path15: {
        plotNumber: '15',
        plotSize: '1046.73Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path16: {
        plotNumber: '16',
        plotSize: '835.21Sqyards',
        plotFacing: 'South',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path17: {
        plotNumber: '17',
        plotSize: '194.58Sqyards',
        plotFacing: 'South',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path18: {
        plotNumber: '18',
        plotSize: '171.06Sqyards',
        plotFacing: 'South',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path19: {
        plotNumber: '19',
        plotSize: '154.45Sqyards',
        plotFacing: 'South',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path20: {
        plotNumber: '20',
        plotSize: '209.56Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path21: {
        plotNumber: '21',
        plotSize: '127.56Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path22: {
        plotNumber: '22',
        plotSize: '122.08Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path23: {
        plotNumber: '23',
        plotSize: '127.07Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path24: {
        plotNumber: '24',
        plotSize: '119.09Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path25: {
        plotNumber: '25',
        plotSize: '124.02Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path26: {
        plotNumber: '26',
        plotSize: '128.14Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path27: {
        plotNumber: '27',
        plotSize: '132.26Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path28: {
        plotNumber: '28',
        plotSize: '136.38Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path29: {
        plotNumber: '29',
        plotSize: '140.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path30: {
        plotNumber: '30',
        plotSize: '144.62Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path31: {
        plotNumber: '31',
        plotSize: '148.75Sqyards',
        plotFacing: 'West',
        name: 'Suresh',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path32: {
        plotNumber: '32',
        plotSize: '287.23Sqyards',
        plotFacing: 'West',
        name: 'Neeraja',
        profession: 'Doctor',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path33: {
        plotNumber: '33',
        plotSize: '307.73Sqyards',
        plotFacing: 'East',
        name: 'Saroja',
        profession: 'Doctor',
        status: 'Booked',
        residentOff: 'Guntur',
    },
    path34: {
        plotNumber: '34',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Yosebhu',
        profession: 'Farmer',
        status: 'Sold',
        residentOff: 'Vegendla',
    },
    path35: {
        plotNumber: '35',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Durga Rao',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Vegendla',
    },
    path36: {
        plotNumber: '36',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path37: {
        plotNumber: '37',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path38: {
        plotNumber: '38',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path39: {
        plotNumber: '39',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path40: {
        plotNumber: '40',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path41: {
        plotNumber: '41',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Rajani',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Alluru',
    },
    path42: {
        plotNumber: '42',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Shareef.SK',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path43: {
        plotNumber: '43',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path44: {
        plotNumber: '44',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Marthamma',
        profession: 'Farmer',
        status: 'Sold',
        residentOff: 'Reddy Pallem',
    },
    path45: {
        plotNumber: '45',
        plotSize: '249.87Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path46: {
        plotNumber: '46',
        plotSize: '161.89Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path47: {
        plotNumber: '47',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path48: {
        plotNumber: '48',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Subba Rao',
        profession: 'Farmer',
        status: 'Sold',
        residentOff: 'Vegendla',
    },
    path49: {
        plotNumber: '49',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path50: {
        plotNumber: '50',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Siva Krishna Reddy',
        profession: 'Farmer',
        status: 'Booked',
        residentOff: 'Vellaturu',
    },
    path51: {
        plotNumber: '51',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path52: {
        plotNumber: '52',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path53: {
        plotNumber: '53',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path54: {
        plotNumber: '54',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path55: {
        plotNumber: '55',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Manasa Kumari',
        profession: 'Business',
        status: 'Booked',
        residentOff: 'Vellaturu',
    },
    path56: {
        plotNumber: '56',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path57: {
        plotNumber: '57',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path58: {
        plotNumber: '58',
        plotSize: '285.24Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path59: {
        plotNumber: '59',
        plotSize: '233.59Sqyards',
        plotFacing: 'East',
        name: 'Gowtham Kumar',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Guntur',
    },

    path60: {
        plotNumber: '60',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Ramesh',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path61: {
        plotNumber: '61',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Ealisha Rani',
        profession: 'Teacher',
        status: 'Booked',
        residentOff: 'Bapatla',
    },
    path62: {
        plotNumber: '62',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Mahesh',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Vijayawada',
    },
    path63: {
        plotNumber: '63',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Kiran Kumar ',
        profession: 'Doctor',
        status: 'Sold',
        residentOff: 'Bapatla',
    },
    path64: {
        plotNumber: '64',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Janaki Ram',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Tenali',
    },
    path65: {
        plotNumber: '65',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Vasanthi',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Khajipalem',
    },
    path66: {
        plotNumber: '66',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Swarna Latha',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Chandol',
    },
    path67: {
        plotNumber: '67',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: '',
        profession: '',
        status: 'Available',
        residentOff: '',
    },
    path68: {
        plotNumber: '68',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: '',
        profession: '',
        status: 'Available',
        residentOff: '',
    },
    path69: {
        plotNumber: '69',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Jayanthi',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Chebrolu',
    },
    path70: {
        plotNumber: '70',
        plotSize: '187.68Sqyards',
        plotFacing: 'East',
        name: 'Suri Babu',
        profession: 'Farmer',
        status: 'Sold',
        residentOff: 'Vegendla',
    },
    path71: {
        plotNumber: '71',
        plotSize: '240.18Sqyards',
        plotFacing: 'East',
        name: 'Bhagya Lakshmi',
        profession: 'Nurse',
        status: 'Sold',
        residentOff: 'Ponnuru',
    },
    path72: {
        plotNumber: '72',
        plotSize: '192.98Sqyards',
        plotFacing: 'East',
        name: 'Vijaya Lakshmi ',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path73: {
        plotNumber: '73',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Ephrayam',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Narakoduru',
    },
    path74: {
        plotNumber: '74',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Gopi',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Khajipalem',
    },
    path75: {
        plotNumber: '75',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Koteswari',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Vegendla',
    },
    path76: {
        plotNumber: '76',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path77: {
        plotNumber: '77',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path78: {
        plotNumber: '78',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path79: {
        plotNumber: '79',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Siva Krishna',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Bapatla',
    },
    path80: {
        plotNumber: '80',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path81: {
        plotNumber: '81',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Madhuri',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path82: {
        plotNumber: '82',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path83: {
        plotNumber: '83',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Rama Devi',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Macharla',
    },
    path84: {
        plotNumber: '84',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path85: {
        plotNumber: '85',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Ashok Yadav',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Bapatla',
    },
    path86: {
        plotNumber: '86',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Imarn.SK ',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Hyderabad',
    },
    path87: {
        plotNumber: '87',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Janaki',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Ponnur',
    },
    path88: {
        plotNumber: '88',
        plotSize: '218.50Sqyards',
        plotFacing: 'East',
        name: 'Srinivasa Rao',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path89: {
        plotNumber: '89',
        plotSize: '216.73Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    
    },
    path90: {
        plotNumber: '90',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Padmavathi',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Vegendla',
    },
    path91: {
        plotNumber: '91',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Naveen Kumar',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Repalle',
    },
    path92: {
        plotNumber: '92',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path93: {
        plotNumber: '93',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Kalpana',
        profession: 'Teacher',
        status: 'Available',
        residentOff: 'Bapatla',
    },
    path94: {
        plotNumber: '94',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path95: {
        plotNumber: '95',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path96: {
        plotNumber: '96',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path97: {
        plotNumber: '97',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',    },
    path98: {
        plotNumber: '98',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path99: {
        plotNumber: '99',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path100: {
        plotNumber: '100',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Punna Rao',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path101: {
        plotNumber: '101',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Krishna Murthi',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path102: {
        plotNumber: '102',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Prasanna',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Perecharla',
    },
    path103: {
        plotNumber: '103',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path104: {
        plotNumber: '104',
        plotSize: '217.82Sqyards',
        plotFacing: 'West',
        name: 'Karthik Babu',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Palakaluru',
    },
    path105: {
        plotNumber: '105',
        plotSize: '294.57Sqyards',
        plotFacing: 'East',
        name: 'Rama Krishna',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Palakaluru',
    },
    path106: {
        plotNumber: '106',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Ravi Kumar',
        profession: 'Business',
        status: 'Sold',
        residentOff: 'Ponnur',
    },
    path107: {
        plotNumber: '107',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path108: {
        plotNumber: '108',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Sai Kumar',
        profession: 'Business',
        status: 'Booked',
        residentOff: 'Ponnur',
    },
    path109: {
        plotNumber: '109',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path110: {
        plotNumber: '110',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path111: {
        plotNumber: '111',
        plotSize: '151.47Sqyards',
        plotFacing: 'East',
        name: 'Nagalakshmi',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Tadiparthi',
    },
    path112: {
        plotNumber: '112',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Malleswarao',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Battiprolu',
    },
    path113: {
        plotNumber: '113',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path114: {
        plotNumber: '114',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path115: {
        plotNumber: '115',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path116: {
        plotNumber: '116',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path117: {
        plotNumber: '117',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Siva Kumari',
        profession: 'House Wife',
        status: 'Booked',
        residentOff: 'Khajipalem',
    },
    path118: {
        plotNumber: '118',
        plotSize: '133.51Sqyards',
        plotFacing: 'East',
        name: 'Sardar.SK',
        profession: 'Employee',
        status: 'Sold',
        residentOff: 'Munipalli',
    },
    path119: {
        plotNumber: '119',
        plotSize: '270.58Sqyards',
        plotFacing: 'North',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path120: {
        plotNumber: '120',
        plotSize: '143.73Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path121: {
        plotNumber: '121',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path122: {
        plotNumber: '122',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path123: {
        plotNumber: '123',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path124: {
        plotNumber: '124',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path125: {
        plotNumber: '125',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path126: {
        plotNumber: '126',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path127: {
        plotNumber: '127',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path128: {
        plotNumber: '128',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path129: {
        plotNumber: '129',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path130: {
        plotNumber: '130',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path131: {
        plotNumber: '131',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path132: {
        plotNumber: '132',
        plotSize: '133.51Sqyards',
        plotFacing: 'West',
        name: 'Babu.SK',
        profession: 'Farmer',
        status: 'Booked',
        residentOff: 'Vegendla',
    },
    path133: {
        plotNumber: '133',
        plotSize: '181.98Sqyards',
        plotFacing: 'West',
        name: 'Renuka Devi',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Nallapadu',
    },
    path134: {
        plotNumber: '134',
        plotSize: '286.99Sqyards',
        plotFacing: 'East',
        name: 'Harish',
        profession: ' Employee',
        status: 'Booked',
        residentOff: 'Guntur',
    },
    path135: {
        plotNumber: '135',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Swarupa',
        profession: 'Teacher',
        status: 'Sold',
        residentOff: 'Tenali',
    },
    path136: {
        plotNumber: '136',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path137: {
        plotNumber: '137',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path138: {
        plotNumber: '138',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Suvarna Keerthana',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Hyderabad',
    },
    path139: {
        plotNumber: '139',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Sparjan',
        profession: 'Railway',
        status: 'Sold',
        residentOff: 'Guntur',
    },
    path140: {
        plotNumber: '140',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path141: {
        plotNumber: '141',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Surendra',
        profession: 'Employee',
        status: 'Booked',
        residentOff: 'Revendrapadu',
    },
    path142: {
        plotNumber: '142',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: 'Naga Teja',
        profession: 'Police',
        status: 'Sold',
        residentOff: 'Ongole',
    },
    path143: {
        plotNumber: '143',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path144: {
        plotNumber: '144',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path145: {
        plotNumber: '145',
        plotSize: '150.15Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path146: {
        plotNumber: '146',
        plotSize: '171.44Sqyards',
        plotFacing: 'East',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path147: {
        plotNumber: '147',
        plotSize: '340.04Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path148: {
        plotNumber: '148',
        plotSize: '315.97Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path149: {
        plotNumber: '149',
        plotSize: '310.73Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path150: {
        plotNumber: '150',
        plotSize: '305.50Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path151: {
        plotNumber: '151',
        plotSize: '300.26Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    },
    path152: {
        plotNumber: '152',
        plotSize: '295.02Sqyards',
        plotFacing: 'West',
        name: '-',
        profession: '-',
        status: 'Available',
        residentOff: '-',
    }
    
   

    

};

export default pathDetails;
